### ISSUE TITLE
*Disease code* Hidradenitis Suppurativa

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#1]
It is proposed to use a codelists based on [READ codes from Schonmann et al](https://datacompass.lshtm.ac.uk/1213/). If people are happy (use an use emojis!) we will send to TPP for mapping to CTV3.

Once it is returned I will upload here for discussion and sign off.

**Comment by brianmackenna** [comment]
The following template should be completed the first time a codelist is developed and uploaded to https://codelists.opensafely.org/



DEFINITION: 


CODE LISTS: 
Upload excel file here

This was created , through the following strategy: 


   
FLEXIBILITY NEEDED BETWEEN STUDIES: 

EFFECTS ON COHORT SELECTION: 
POTENTIAL BIASES: 

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: 

SHARED WITH WIDER TEAM:

FINAL SIGN OFF DATE (and apply label):

**Comment by brianmackenna** [comment]
This is the mapped list that TPP returned and have additionally added high-level snomed


CTV3ID | CTV3PreferredTermDesc | CTV3Source
-- | -- | --
M25y1 | Hidradenitis (& hidradenitis suppurativa) | High_Level_SNOMED
XE1BM | Hidradenitis | CTV3Map_Code_And_Term
XE1BM | Hidradenitis | CTV3Map_Code_Only
XE1Cw | (Sweat gland prob NOS) or (dyshidros) or (hydraden (&   supp) | High_Level_SNOMED
Xa9CY | Hidradenitis suppurativa | CTV3Map_Code_And_Term
Xa9CY | Hidradenitis suppurativa | CTV3Map_Code_Only



@sinlangan

**Comment by sinlangan** [comment]
Brian, looks good to me, thanks.

**Comment by brianmackenna** [comment]
Excellent. http://codelists.opensafely.org/ is just getting some upgrades to support version control. Will add once that is done.

**Comment by brianmackenna** [comment]
@sinlangan  Final(ish) [list and methodology here](https://codelists.opensafely.org/codelist/opensafely/hidradenitis-suppurativa/2020-08-03-draft/). All good?

**Comment by sinlangan** [comment]
Yes thanks


________________________________

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/hidradenitis-suppurativa/2020-08-03/
