### ISSUE TITLE
*Disease code* Crohn's disease

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#10]
[Initial Crohn's disease code list using CTV3](https://github.com/opensafely/immunosuppressant-meds-research/files/5029680/crossimid-crohns-disease.csv.txt). Note the file is named .txt because GitHub does not support attaching csv files to issues.

[Also available here](https://github.com/NikNakk/immunosuppressant-meds-research/blob/ibd-codelist/codelists/crossimid-crohns-disease.csv).

**Comment by katetheyogi** [comment]
Just reviewed this and it looks good to me.

**Comment by NikNakk** [comment]
Awaiting upload to https://codelists.opensafely.org/

**Comment by brianmackenna** [comment]
Could someone sense check to see if still ok and document methodology please?

https://codelists.opensafely.org/codelist/opensafely/crohns-disease/223a39f5/

**Comment by AnnaB45** [comment]
@NikNakk - think this is just waiting for your review and then it can be closed.

**Comment by NikNakk** [comment]
Happy to sign off. Methodology was documented in #12.
