### ISSUE TITLE
*Disease code* ulcerative colitis

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#11]
[Initial ulcerative disease code list using CTV3](https://github.com/opensafely/immunosuppressant-meds-research/files/5029699/crossimid-ulcerative-colitis.csv.txt). Note the file is named .txt because GitHub does not support attaching csv files to issues.

[Also available here](https://github.com/NikNakk/immunosuppressant-meds-research/blob/ibd-codelist/codelists/crossimid-ulcerative-colitis.csv).

**Comment by katetheyogi** [comment]
Just reviewed this and it looks good to me.

**Comment by NikNakk** [comment]
Awaiting upload to https://codelists.opensafely.org/

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/ulcerative-colitis/3b49ad2a/

Can someone please write the methodology and just  sense check it is still ok please? (been awhile since it was created!)

**Comment by brianmackenna** [comment]
I have published the list https://codelists.opensafely.org/codelist/opensafely/ulcerative-colitis/3b49ad2a/#full-list

When publishing the list is a lot shorter than I would expect. Should we not be including codes like `XM1RP - history of ulcerative colitis` ? 

Fuller list at https://codelists.opensafely.org/ctv3/?q=ulcerative+colitis&submit=Search (tool was not available when you actually built the codelist)

**Comment by AnnaB45** [comment]
@NikNakk and @brianmackenna - from the email chain it looks like history of codes shouldn't be included. If so, can this issue be closed now?

**Comment by brianmackenna** [comment]
I think history of is fine but that was just an example. I can see two codes that potentially we may wish to include
- https://codelists.opensafely.org/ctv3/concept/N0454/
- https://codelists.opensafely.org/ctv3/concept/N0310/

Also wondering if other term searches may throw other things up?

**Comment by brianmackenna** [comment]
(we should run the current study regardless of sorting this study)
