### ISSUE TITLE
*Disease code* inflammatory bowel disease unclassified (IBD-U)

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#12]
[Initial IBD-U code list using CTV3](https://github.com/opensafely/immunosuppressant-meds-research/files/5029708/crossimid-inflammatory-bowel-disease-unclassified.csv.txt).
Note the file is named .txt because GitHub does not support attaching csv files to issues.

[Also available here](https://github.com/NikNakk/immunosuppressant-meds-research/blob/ibd-codelist/codelists/crossimid-inflammatory-bowel-disease-unclassified.csv).

This codelist is intended to be used alongside the Crohn's and ulcerative colitis code lists, such that patients are only given a label of IBD-U where they do not carry one of the more specific disease codes in those lists.

**Comment by brianmackenna** [comment]
@NikNakk would you be able to describe the methodology on how the codes were selected/where they came from please?

**Comment by NikNakk** [comment]
Charlie Lees and I used the NHS Read Term browser to go through all codes within CTV3 found on searches of Crohn, colitis and inflammatory bowel disease. We also browsed the hierarchy up to parent terms to check siblings of the relevant codes for any that had been missed. The distinction between the Crohn's and ulcerative colitis codes is relatively clear cut. There are two codes that do not make the distinction between Crohn's and UC, in particular X303k which maps to the ICD10 code K52.3. This condition is more correctly described as inflammatory bowel disease unclassified in patients who have not had a colectomy; indeterminate colitis is reserved for those who have had a colectomy and in whom it remains impossible to refine the diagnosis as Crohn's or UC. However, ICD10 (and hence CTV3) do not make this distinction.

We have assumed that the majority of patients with Crohn's and UC will have one of the relevant disease specific codes. Patients without a Crohn's or UC code but who have one of the IBD-U codes should be labelled as IBD-U.

For the current cross-IMID analysis we will collapse all of the IBD subtypes into a single IBD codelist. However, for descriptive reporting it would be useful to report the numbers of patients in each of the three subtypes.

Note this is also relevant for #10 and #11.

**Comment by brianmackenna** [comment]
Thanks @NikNakk . @inglesp and team are working on something that will hopefully make this easier in the future.

We just need an independent check now. @katetheyogi @myatesrheum  but feel free to swap with someone else in the group!

**Comment by katetheyogi** [comment]
Planning on checking through tomorrow.

**Comment by katetheyogi** [comment]
Looks absolutely fine to me. I was settling down to tackle a LONG list of codes. Absolutely delighted to find only 2!

**Comment by NikNakk** [comment]
There’s also #10 and #11. 

BW

Nick

**Comment by katetheyogi** [comment]
Aaah... I thought it seemed too easy. I'll do them first thing tomorrow.

**Comment by NikNakk** [comment]
Awaiting upload to https://codelists.opensafely.org/

**Comment by brianmackenna** [comment]
Just needs a final sense check and the meatdata/methodology updating

https://codelists.opensafely.org/codelist/opensafely/inflammatory-bowel-disease-unclassified/092ac6c0/

**Comment by brianmackenna** [comment]
method as above to add also for #10 and #11

**Comment by brianmackenna** [comment]
https://codelists.opensafely.org/codelist/opensafely/inflammatory-bowel-disease-unclassified/092ac6c0/ 

I can't see account for Charlie - to be added one account created
