### ISSUE TITLE
*Medication Codes* Separate DMARDs medication list

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#14]
Separate the opensafely-dmards.csv list into separate codelists for each class of immunosuppressant. Note this has already been done in https://github.com/NikNakk/immunosuppressant-meds-research/tree/master/crossimid-codelists

**Comment by brianmackenna** [comment]
Thanks @NikNakk  phenomenal amount of work.

Did you manually split these up or have you script?

**Comment by NikNakk** [comment]
Hi @brianmackenna, manually through some sorting and filtering in Excel. I would often do something like this in script, but for this as a one off task it felt more efficient to do it in Excel rather that iteratively writing RegExes which would probably have been my approach otherwise.

**Comment by brianmackenna** [comment]
That's great. Hopefully no need for scripts soon as we are building tools to build codelists.

Just to confirm is it off this list you filtered?

https://github.com/ebmdatalab/immunosuppressant-covid-codelist-notebook/blob/master/notebooks/immunosuppressants.ipynb

**Comment by brianmackenna** [comment]
Is this list still required? It has been surpassed I think by high cost drugs codelists?

Perhaps it is just single codelists for primary care dm+d list based on this? https://codelists.opensafely.org/codelist/opensafely/dmards/2020-06-23/

**Comment by NikNakk** [comment]
This issue was about the separated primary care drugs. The separate lists are still in the crossimid-codelists, but we’ve not moved them forwards to the codelists site because you’d suggested there was better way now of automatically deriving them.

Best wishes,

Nick Kennedy
________________________________

**Comment by brianmackenna** [comment]
closing - individual issues have been opend.
