### ISSUE TITLE
*High cost drug codes* dupilumab

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#19]
High cost drugs codelist for anti-IL4

**Comment by katetheyogi** [comment]
SL, CS and KM checked and codelists for dupilumab all look good.

**Comment by NikNakk** [comment]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of dupilumab.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- dupilumab
- dupixent

All drug name values that contain at least one of the above strings are included in the dupilumab group and assigned the VTM (virtual therapeutic moiety) code 395279009.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* dupilumab](https://github.com/opensafely/immunosuppressant-meds-research/issues/19)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: dupilumab](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-dupilumab-drug-names.csv)

**Comment by AnnaB45** [comment]
@NikNakk Is this included in the immunosuppressants study definition? If yes, has the codelist been reviewed?

**Comment by NikNakk** [comment]
@AnnaB45 No, not any more. We may need it in future, but we did not review it on Friday. @sinlangan and Catherine would be the best people to review.

**Comment by brianmackenna** [comment]
This looks good to me @AnnaB45 .

**Comment by sinlangan** [comment]
Agree, confirm this looks good.

**Comment by AnnaB45** [comment]
Added the codelist to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-dupilumab/3386a994/).
Closed issue.
