### ISSUE TITLE
Psoriatic arthritis

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#2]
To be developed. Guidance on codelists development is [available here in documentation folder](https://github.com/opensafely/documentation/blob/master/codelist%20creation.md).

The following template should be completed the first time a codelist is developed and uploaded to https://codelists.opensafely.org/

DEFINITION: 

CODE LISTS: 
Upload excel file here

This was created , through the following strategy: 

   
FLEXIBILITY NEEDED BETWEEN STUDIES: 

EFFECTS ON COHORT SELECTION: 
POTENTIAL BIASES: 

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: 

SHARED WITH WIDER TEAM:

FINAL SIGN OFF DATE (and apply label):

**Comment by sinlangan** [comment]
See comments in psoriasis code list, identified in column D with variable 2.  Will check with James if there are additional codes

**Comment by NikNakk** [comment]
This is handled by #7

**Comment by brianmackenna** [comment]
Reopening as per discussion on weekly call about keeping seperate.

**Comment by myatesrheum** [comment]
Psoriatic Arthritis code built in code builder (snomed)

[mark-yates-psoriatic-arthritis-2020-10-21T09-22-03.txt](https://github.com/opensafely/immunosuppressant-meds-research/files/5414757/mark-yates-psoriatic-arthritis-2020-10-21T09-22-03.txt)

@brianmackenna

**Comment by myatesrheum** [comment]
DEFINITION: Psoriatic Arthritis code (snomed)

CODE LISTS:

[mark-yates-psoriatic-arthritis-2020-10-21T09-22-03.txt](https://github.com/opensafely/immunosuppressant-meds-research/files/5414854/mark-yates-psoriatic-arthritis-2020-10-21T09-22-03.txt)

This was created , through the following strategy: GitHub code Builder

FLEXIBILITY NEEDED BETWEEN STUDIES: None

EFFECTS ON COHORT SELECTION: Caution needed with overlap with other axial spondyloarthritis

POTENTIAL BIASES: misclassification with AS overlap

CLINICAL SIGN OFF & DATE: MY 21/10/2020

EPIDEMIOLOGY SIGN OFF & DATE: JG 21/10/2020

SHARED WITH WIDER TEAM: @brianmackenna

FINAL SIGN OFF DATE (and apply label):

**Comment by brianmackenna** [comment]
This looks good to me! Do you have screen shots of the term searches and I'll add to the methodology section? e.g.

![image](https://user-images.githubusercontent.com/40460354/96718671-3e8c2880-13a0-11eb-8396-6251717977d1.png)

Would you also be able to download the csv and share (email is fine) with me as well please? When changing between file formats Snomed codes can get changed

![image](https://user-images.githubusercontent.com/40460354/96718886-8f038600-13a0-11eb-8420-57c0fddeb626.png)

**Comment by brianmackenna** [comment]
@myatesrheum  and James (who I don't think has accepted invite) are you happy with description?

https://codelists.opensafely.org/codelist/opensafely/psoriatic-arthritis/2020-10-21/

**Comment by myatesrheum** [comment]
Looks good to me

**Comment by brianmackenna** [comment]
This is ctv3 version created by mapping - look ok?

| snomedct_id | snomedct_name                                                                  | ctv3_id | ctv3_name                                                    |
|-------------|--------------------------------------------------------------------------------|---------|--------------------------------------------------------------|
| 1.56E+08    | Psoriatic arthritis (disorder)                                                 | M160.   | Psoriatic arthritis                                          |
| 19514005    | Arthritis mutilans (disorder)                                                  | X7027   | Psoriatic arthritis - destructive type                       |
| 2.01E+08    | Psoriatic arthritis with spine involvement (disorder)                          | M1600   | Psoriatic arthritis with spine involvement                   |
| 2.4E+08     | Juvenile psoriatic arthritis (disorder)                                        | X701u   | Juvenile psoriatic arthritis                                 |
| 2.4E+08     | Juvenile psoriatic arthritis with psoriasis (disorder)                         | X701v   | Juvenile psoriatic arthritis with psoriasis                  |
| 2.4E+08     | Juvenile psoriatic arthritis without psoriasis (disorder)                      | X701w   | Juvenile psoriatic arthritis without psoriasis               |
| 2.4E+08     | Psoriatic arthritis with distal interphalangeal joint involvement   (disorder) | X7026   | Psoriatic arthritis with distal interphalangeal joint involv |
| 2.4E+08     | Psoriatic dactylitis (disorder)                                                | X7028   | Psoriatic dactylitis                                         |
| 33339001    | Psoriasis with arthropathy (disorder)                                          | M160.   | Psoriatic arthritis                                          |
| 33339001    | Psoriasis with arthropathy (disorder)                                          | M160z   | Psoriatic arthropathy NOS                                    |
| 33339001    | Psoriasis with arthropathy (disorder)                                          | Nyu13   | [X]Other psoriatic arthropathies                             |

**Comment by myatesrheum** [comment]
Yes looks fine to me

**Comment by sinlangan** [comment]
Yes, looks good, thanks!

**Comment by NikNakk** [comment]
https://github.com/NikNakk/immunosuppressant-meds-research/blob/master/codelists/crossimid-psoriasis.csv

**Comment by NikNakk** [comment]
Looks like this can be closed - exists at https://codelists.opensafely.org/codelist/opensafely/psoriatic-arthritis/2020-10-21/#full-list

Reviewed today by @sinlangan, @myatesrheum, @NikNakk
