### ISSUE TITLE
*Medication codes* mesalazine

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#26]

**Comment by brianmackenna** [comment]
@richiecroker could you take a look at this codelist please?

**Comment by brianmackenna** [comment]
Q for the group - do we want to include all preparations of mesalazine here? It can be used in acute attacks and longer term to keep remission maintained.
 

The [BNF has a good list](https://bnf.nice.org.uk/drug/mesalazine.html) - basically do we just include orals or also things like enemas etc.

**Comment by richiecroker** [comment]
also, do we just need to include mesalazine or related drugs as well, e.g. olsalazine?

**Comment by NikNakk** [comment]
All oral mesalazine, olsalazine, balsalazide. Sulfasalazine should be in a separate code list. We can probably leave rectal mesalazine preparations out for now (or they would belong separately).

Best wishes,

Nick Kennedy
________________________________

**Comment by brianmackenna** [comment]
I have made a new codelist of "Newer aminosalicylates for IBD" which includes all oral forms of mesalazine, olsalazine, balsalazide. I have made a new issue for sulfasalazine #79 

https://codelists.opensafely.org/codelist/opensafely/newer-aminosalicylates-for-ibd/416c77a8/

Need to confirm that

- exclude rectal preps
- the name is somewhat sensible for this group (I've taken from BNF)
- accuracy of codelist

**Comment by brianmackenna** [comment]
confirmed three things above on weekly working group call

**Comment by brianmackenna** [comment]
dm+d list https://codelists.opensafely.org/codelist/opensafely/newer-aminosalicylates-for-ibd-dmd/4c377780/#full-list
