### ISSUE TITLE
*Disease Code* Ankylosing Spodylitis

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#3]
To be developed. Guidance on codelists development is [available here in documentation folder](https://github.com/opensafely/documentation/blob/master/codelist%20creation.md).

The following template should be completed the first time a codelist is developed and uploaded to https://codelists.opensafely.org/

DEFINITION: 

CODE LISTS: 
Upload excel file here

This was created , through the following strategy: 

   
FLEXIBILITY NEEDED BETWEEN STUDIES: 

EFFECTS ON COHORT SELECTION: 
POTENTIAL BIASES: 

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: 

SHARED WITH WIDER TEAM:

FINAL SIGN OFF DATE (and apply label):

**Comment by jamesgalloway** [comment]
Psoriatic arthritis and ankylosing spondylitis.
[CTV3.docx](https://github.com/opensafely/immunosuppressant-meds-research/files/4949240/CTV3.docx)

**Comment by brianmackenna** [comment]
Thanks. Q for you and @sinlangan 

Are we keeping together as a single codelist or are we separating out individual lists as per the draft protocol?

**Comment by sinlangan** [comment]
@brianmackenna and @jamesgalloway, we should separate out. Unlikely to have PSA without psoriasis, but PSA would trump psoriasis.

**Comment by jamesgalloway** [comment]
Y70ET      C      Juvenile ankylosin spondylitis  /    Juvenile ankylosing spondylitis      
Y70EU      O      Juvenile AS - ank spondylitis   /   Juvenile AS - ankylosing spondylitis      
Y70Ef      C      Ankylosing spondylitis            
Y70Eh      C      Idiopathic ankylos spondylit  /    Idiopathic ankylosing spondylitis      
Y70Ei      C      AS - Ankylosing spondylitis            
Y70Ej      C      AS with organ / system involve   /   Ankylosing spondylitis with organ / system involvement      
Y70Ek      C      AS with multisystem involvemen   /   Ankylosing spondylitis with multisystem involvement      
Y70qg      C      Ankylosing verteb hyperostosis  /    Ankylosing vertebral hyperostosis      
YMKxe      O      Spondylitis -ankylosing            
YaaZ4      C      AS-Juvenile ankylos spondylit   /   AS - Juvenile ankylosing spondylitis      
YaxFh      C      Axial spondyloarthritis            
Y70EZ      C      Seronegative arthritis

**Comment by myatesrheum** [comment]
AxialSpa codes built in github builder (snomed)
[mark-yates-axial-spondyloarthritis-2020-10-21T09-07-35.txt]
(https://github.com/opensafely/immunosuppressant-meds-research/files/5414703/mark-yates-axial-spondyloarthritis-2020-10-21T09-07-35.txt)

**Comment by myatesrheum** [comment]
DEFINITION: Axial Spondyloarthritis code (snomed)

CODE LISTS:

[mark-yates-axial-spondyloarthritis-2020-10-21T09-07-35.txt](https://github.com/opensafely/immunosuppressant-meds-research/files/5414814/mark-yates-axial-spondyloarthritis-2020-10-21T09-07-35.txt)

This was created , through the following strategy: GitHub code Builder

FLEXIBILITY NEEDED BETWEEN STUDIES: None

EFFECTS ON COHORT SELECTION: Caution needed with overlap with psoriatic spondyloarthritis

POTENTIAL BIASES: misclassification with PsA overlap

CLINICAL SIGN OFF & DATE: MY 21/10/2020

EPIDEMIOLOGY SIGN OFF & DATE:  JG 21/10/2020

SHARED WITH WIDER TEAM: @brianmackenna 

FINAL SIGN OFF DATE (and apply label):

**Comment by NikNakk** [comment]
Reviewed again today - awaiting upload to codelists.opensafely.org

**Comment by brianmackenna** [comment]
@myatesrheum  just to confirm this is the codelist that we should publish?

https://codelists.opensafely.org/codelist/user/mark-yates/axial-spondyloarthritis/3da730d4/#tree

**Comment by AnnaB45** [comment]
@brianmackenna and @jamesgalloway , which codelist should be used for this disease?
There's [ankylosing spondylitis](https://codelists.opensafely.org/codelist/opensafely/ankylosing-spondylitis/701b538a/) and [axial spondyloarthritis](https://codelists.opensafely.org/codelist/user/mark-yates/axial-spondyloarthritis/3da730d4/#tree) on OpenSAFELY codelists.

**Comment by jamesgalloway** [comment]
Use Axial Spondyloarthritis - as this is the overarching category that includes Ankylosing Spondylitis - @AnnaB45

**Comment by AnnaB45** [comment]
Thanks @jamesgalloway - can you confirm you're happy with the [Axial Spondyloarthritis](https://codelists.opensafely.org/codelist/user/mark-yates/axial-spondyloarthritis/3da730d4/#tree) codelist on OpenSAFELY codelists. Then we can close the issue.

**Comment by jamesgalloway** [comment]
> Thanks @jamesgalloway - can you confirm you're happy with the [Axial Spondyloarthritis](https://codelists.opensafely.org/codelist/user/mark-yates/axial-spondyloarthritis/3da730d4/#tree) codelist on OpenSAFELY codelists. Then we can close the issue.

This codelist is reviewed and confirmed.
