### ISSUE TITLE
*High cost drug codes* adalimumab

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#36]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of adalimumab.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- adalimumab
- amgevita
- hyrimoz
- humira
- idacio
- imraldi

All drug name values that contain at least one of the above strings are included in the adalimumab group and assigned the VTM (virtual therapeutic moiety) code 398728003.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* adalimumab](https://github.com/opensafely/immunosuppressant-meds-research/issues/36)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: adalimumab](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-adalimumab-drug-names.csv)

**Comment by NikNakk** [comment]
Reviewed on 19/02/2021 by @niknakk and Charlie Lees

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-adalimumab/6eec91b5/)

**Comment by NikNakk** [comment]
Reviewed by @AnnaB45, @sinlangan, @myatesrheum, @NikNakk, @jamesgalloway

**Comment by NikNakk** [comment]
Note there are some entries for 'gain share'; these should still successfully identify people exposed to the drug, but may effectively be duplicate events.

**Comment by AnnaB45** [comment]
Updated reviewers on OpenSAFELY Codelists and closed issue.
