### ISSUE TITLE
*High cost drug codes* aflibercept

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#37]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of aflibercept.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- aflibercept
- eylea
- zaltrap

All drug name values that contain at least one of the above strings are included in the aflibercept group and assigned the VTM (virtual therapeutic moiety) code 21674911000001100.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* aflibercept](https://github.com/opensafely/immunosuppressant-meds-research/issues/37)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: aflibercept](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-aflibercept-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-aflibercept/55dd1e80/).

**Comment by NikNakk** [comment]
Not needed for this project
