### ISSUE TITLE
*High cost drug codes* anakinra

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#39]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of anakinra.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- anakinra
- kineret

All drug name values that contain at least one of the above strings are included in the anakinra group and assigned the VTM (virtual therapeutic moiety) code 395279009.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* anakinra](https://github.com/opensafely/immunosuppressant-meds-research/issues/39)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: anakinra](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-anakinra-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-anakinra/23be3816/).

**Comment by NikNakk** [comment]
Reviewed by @AnnaB45, @sinlangan, @myatesrheum, @NikNakk, @jamesgalloway, though not needed for this project.
