### ISSUE TITLE
*Disease code* Atopic eczema

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#4]
To be developed. Guidance on codelists development is [available here in documentation folder](https://github.com/opensafely/documentation/blob/master/codelist%20creation.md).

The following template should be completed the first time a codelist is developed and uploaded to https://codelists.opensafely.org/

DEFINITION: 

CODE LISTS: 
Upload excel file here

This was created , through the following strategy: 

   
FLEXIBILITY NEEDED BETWEEN STUDIES: 

EFFECTS ON COHORT SELECTION: 
POTENTIAL BIASES: 

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: 

SHARED WITH WIDER TEAM:

FINAL SIGN OFF DATE (and apply label):

**Comment by sinlangan** [comment]
Brian, the atopic eczema Read codes are . at, https://datacompass.lshtm.ac.uk/1281/1/readcodes-eczemaDx-exca.txt. The treatment codes are at https://datacompass.lshtm.ac.uk/1254/1/final_prodcodes-eczemaRx.txt. The algorithm is based on a record of one diagnostic morbidity code (recorded in either primary or secondary care) and at least two records (on separate days) for eczema therapy (recorded in primary care using Read morbidity codes or prescription data). Eczema therapy included primary care records of (1) morbidity codes for phototherapy and (2) prescriptions for topical emollients,
corticosteroids or calcineurin inhibitors, or oral glucocorticoids, azathioprine, methotrexate, ciclosporin or
mycophenolate.
We identified phototherapy using Read codes in primary care and Office of Population Censuses and Surveys
(OPCS) procedure codes in secondary care. Systemic eczema treatment was identified using primary care
prescription records. Hospital admissions for eczema were identified as any hospitalisation in which an ICD-10
code for eczema was recorded in the primary diagnostic position of any episode associated with the
hospitalization. Reference here in supplementary 3. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7315391/

**Comment by sinlangan** [comment]
Phototherapy codes are  here: https://datacompass.lshtm.ac.uk/1282/1/readcodes-eczemaRx-exca.txt

**Comment by brianmackenna** [comment]
Great. We'll get these mapped to snomed/dm+d. A few questions

1) Are there date limits on the algorithm e.g. is it eczema code `ever` or `last 12 months`?

2) Oral medicines: These are used for a wide variety of conditions and generally in eczema they are only used in severe disease. I'm thinking they may add to false positives for eczema and the topical may be sufficient? Some of the things in the list (e.g. dexamethasone solution) are  unlikely to be used for eczema I think ? Should we restrict to just topicals?

**Comment by brianmackenna** [comment]
Or maybe there's a validation study I haven't seen yet?

**Comment by sinlangan** [comment]
There is, it's at https://pubmed.ncbi.nlm.nih.gov/28428130/. For eczema, code in last three years with two treatments would be best. Won't identify "ever eczema" but will identify "active eczema". Agree Dexamethasone solution unlikely to be used for eczema- would remove.

**Comment by myatesrheum** [comment]
DEFINITION: Atopic Eczema Snomed list 

CODE LISTS:
[mark-yates-atopic-eczema-2020-10-21T16-19-11.xlsx](https://github.com/opensafely/immunosuppressant-meds-research/files/5417330/mark-yates-atopic-eczema-2020-10-21T16-19-11.xlsx)


This was created , through the following strategy: Code builder

![Atopic Eczema](https://user-images.githubusercontent.com/67652831/96748724-d5b5a800-13c1-11eb-8146-f6c0c91dc39b.png)


FLEXIBILITY NEEDED BETWEEN STUDIES: Nil

EFFECTS ON COHORT SELECTION: Needs combining with drug list 

POTENTIAL BIASES: This list is much more expanded than the LSHTM above, let me know if this is incorrect. 

CLINICAL SIGN OFF & DATE:  Needs checking by @sinlangan 

EPIDEMIOLOGY SIGN OFF & DATE: Do you mind having a look @katetheyogi 

SHARED WITH WIDER TEAM:

FINAL SIGN OFF DATE (and apply label):

**Comment by sinlangan** [comment]
@myatesrheum and @brianmackenna, the morbidity code variable seems to have become corrupted. I have highlighted codes I don't think should be included in yellow. How does eczema NOS map across?

The original Read codes are in, 
[readcode_eczema.docx](https://github.com/opensafely/immunosuppressant-meds-research/files/5431657/readcode_eczema.docx) and the edited code list at, 
[mark-yates-atopic-eczema-2020-10-21T16-19-11_sml.xlsx](https://github.com/opensafely/immunosuppressant-meds-research/files/5431658/mark-yates-atopic-eczema-2020-10-21T16-19-11_sml.xlsx)

**Comment by brianmackenna** [comment]
I have had a quick look and the majority of exclusions from @sinlangan appear to be related to "contact dermatitis". @myatesrheum I can't edit your codelist directly but if you look for "parent" like in image below it will exclude large groups related to "contact dermatitis" without having to go through each code individually.

![image](https://user-images.githubusercontent.com/40460354/109930539-aabc5880-7cbf-11eb-8911-ac73baacf81c.png)
