### ISSUE TITLE
*High cost drug codes* belimumab

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#41]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of belimumab.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- belimumab
- benlysta

All drug name values that contain at least one of the above strings are included in the belimumab group and assigned the VTM (virtual therapeutic moiety) code 704193005.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* belimumab](https://github.com/opensafely/immunosuppressant-meds-research/issues/41)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: belimumab](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-belimumab-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-belimumab/719f51ab/).

**Comment by NikNakk** [comment]
Reviewed by @AnnaB45, @sinlangan, @myatesrheum, @NikNakk, @jamesgalloway; not needed for this project.
