### ISSUE TITLE
*High cost drug codes* filgotinib

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#47]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of filgotinib.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- filgotinib
- jyseleca

All drug name values that contain at least one of the above strings are included in the filgotinib group and assigned the VTM (virtual therapeutic moiety) code 39046711000001104.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* filgotinib](https://github.com/opensafely/immunosuppressant-meds-research/issues/47)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: filgotinib](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-filgotinib-drug-names.csv)

**Comment by AnnaB45** [comment]
@NikNakk The link to the codelist in this issue isn't working, looks like the file doesn't exist in the crossimid-codelists area

**Comment by AnnaB45** [comment]
Information from Charlie Lees on above comment "We discussed filgotinib on Friday. The drug licence date (EMA) was only September 2020 and therefore it was felt not necessary to include in codelist."
