### ISSUE TITLE
*Disease Code* Rheumatoid Arthritis

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#5]
A definition of rheumatoid arthritis has been developed previously and is [available here for inspection](https://codelists.opensafely.org/codelist/opensafely/rheumatoid-arthritis/).

Please can this be reviewed for the purposes of this study?

**Comment by myatesrheum** [comment]
Checked by me and JG, no editing required for this study

**Comment by brianmackenna** [comment]
Thanks - confirmed in protocol

https://codelists.opensafely.org/codelist/opensafely/rheumatoid-arthritis/2020-05-12/
