### ISSUE TITLE
*High cost drug codes* ixekizumab

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#51]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of ixekizumab.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- ixekizumab
- taltz

All drug name values that contain at least one of the above strings are included in the ixekizumab group and assigned the VTM (virtual therapeutic moiety) code 32819111000001100.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* ixekizumab](https://github.com/opensafely/immunosuppressant-meds-research/issues/51)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: ixekizumab](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-ixekizumab-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-ixekizumab/2923b802/).

**Comment by AnnaB45** [comment]
@NikNakk Was this one of the codelists we reviewed on Friday?

**Comment by NikNakk** [comment]
Reviewed on 26th Feb by @myatesrheum, @AnnaB45, @NikNakk, @sinlangan and @jamesgalloway.

**Comment by AnnaB45** [comment]
Updated reviewers on OpenSAFELY codelists and closed issue.
