### ISSUE TITLE
*High cost drug codes* methotrexate

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#53]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of methotrexate.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- methotrexate
- nordimet
- zlatal
- methofill
- metoject

All drug name values that contain at least one of the above strings are included in the methotrexate group and assigned the VTM (virtual therapeutic moiety) code 68887009.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* methotrexate](https://github.com/opensafely/immunosuppressant-meds-research/issues/53)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: methotrexate](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-methotrexate-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-methotrexate/7704d197/).

**Comment by NikNakk** [comment]
Amended to exclude `thecal|\biv\b|venous|cyto|aseptic`.

Reviewed by @AnnaB45, @sinlangan, @myatesrheum, @NikNakk, @jamesgalloway

@AnnaB45, please could you update the version on codelists.opensafely.org? I've put the new version back in the crossimid-codelists folder.

**Comment by AnnaB45** [comment]
Uploaded latest version of the codelist and updated reviewers on OpenSAFELY codelists. Closed issue.
