### ISSUE TITLE
*High cost drug codes* omalizumab

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#56]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of omalizumab.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- omalizumab
- xolair

All drug name values that contain at least one of the above strings are included in the omalizumab group and assigned the VTM (virtual therapeutic moiety) code 406442003.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* omalizumab](https://github.com/opensafely/immunosuppressant-meds-research/issues/56)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: omalizumab](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-omalizumab-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-omalizumab/2bd677f8/).

**Comment by NikNakk** [comment]
Not needed for this project.
