### ISSUE TITLE
*Disease code* Inflammatory bowel disease

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#6]
WE have previously developed this [codelist for IBD and it is available here](http://codelists.opensafely.org/codelist/opensafely/inflammatory-bowel-disease/). Please can we confirm if of for purposes of this study?

@inglesp I notice we have also mapped a [snomed version of this list](http://codelists.opensafely.org/codelist/opensafely/inflammatory-bowel-disease-snomed/). Is there anything helpful the reviewer could look at while reviewing above?

**Comment by NikNakk** [comment]
Suggest closing this issue since it has been superceded by the separate issues #10, #11 and #12.
