### ISSUE TITLE
*High cost drug codes* rituximab

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#60]
## Description

This is a list of all the unique values from the Drug Name variable in the High Cost Drugs Dataset that relate to the prescribing of rituximab.

## Methodology

The values in this variable do not follow a coding system so the selection for this codelist is based on the drug name value, after converting all text to lower case, containing one or more of the following strings (these are the generic medicine name and brand names):
    
- rituximab
- rituxmab
- mabthera
- rixathon
- ruxience
- truxima

All drug name values that contain at least one of the above strings are included in the rituximab group and assigned the VTM (virtual therapeutic moiety) code 108809004.

**Comment by NikNakk** [comment]
## References

- [GitHub issue: *High cost drug codes* rituximab](https://github.com/opensafely/immunosuppressant-meds-research/issues/60)
- [Original STATA dofile](https://github.com/opensafely/immunosuppressant-meds-research/issues/29)
- [R script used to produce codelist](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/make_druglists/make_new_druglists_and_metadata.R)
- [Draft codelist: rituximab](https://github.com/opensafely/immunosuppressant-meds-research/tree/master/crossimid-codelists/crossimid-rituximab-drug-names.csv)

**Comment by AnnaB45** [comment]
Added to [OpenSAFELY Codelists](https://codelists.opensafely.org/codelist/opensafely/high-cost-drugs-rituximab/4798ab23/#full-list).

**Comment by NikNakk** [comment]
Reviewed by @AnnaB45, @sinlangan, @myatesrheum, @NikNakk, @jamesgalloway

**Comment by NikNakk** [comment]
Amended to exclude `r-chop`. @AnnaB45 please could you update version on codelists.opensafely.org

**Comment by AnnaB45** [comment]
Uploaded latest codelist and updated reviewers on OpenSAFELY codelists. Closed issue.
