### ISSUE TITLE
*Disease code* Psoriasis

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#7]
We have previously developed this [definition of psoriasis which is available here](https://codelists.opensafely.org/codelist/opensafely/ra-sle-psoriasis/). It is combined with RA / SLE / Psoriais

Please could someone create a psoriasis only list for review?

Separately could they identify codes which we may not want to include in this study. For example it was mentioned that there may be good reason to remove "history of" codes as psoriasis is not permanent. 

We can then test the difference between two lists and see difference in pick up. This will give us a feel for numbers and codelists and also help inform tools that need to be built in future.

**Comment by sinlangan** [comment]
Brian, I have edited. Catherine is now reviewing. In column D we have flagged people that have both psoriasis and PSA.

**Comment by sinlangan** [comment]
[Psoriasis and PSA_final.xlsx](https://github.com/opensafely/immunosuppressant-meds-research/files/5002308/Psoriasis.and.PSA_final.xlsx)
Hi Brian, 
PSA is highlighted here with "2" in column D. By definition have Ps if have PSA, but PSA will trump Ps in analyses.

**Comment by myatesrheum** [comment]
We have built a separate Psoriatic arthritis Snomed codelist, which we can use if needed (see issue list).

**Comment by NikNakk** [comment]
This is my version of the separate psoriasis codes:

https://github.com/NikNakk/immunosuppressant-meds-research/blob/master/crossimid-codelists/crossimid-psoriasis.csv

**Comment by sinlangan** [comment]
Please remove x50jd acropustulosis of infancy

**Comment by NikNakk** [comment]
Done, and reflected in https://github.com/NikNakk/immunosuppressant-meds-research/blob/master/crossimid-codelists/crossimid-psoriasis.csv

**Comment by myatesrheum** [comment]
Also signed off by Catherine Smith in October 2020

**Comment by NikNakk** [comment]
Awaiting upload to https://codelists.opensafely.org/

**Comment by brianmackenna** [comment]
Done https://codelists.opensafely.org/codelist/opensafely/psoriasis/01091de1/#tree @sinlangan you might find tree structure easy way of seeing what included/excluded

Need to add Catherine to authorship once account set up
