### ISSUE TITLE
High cost drugs need updating through rest of STATA do file

### ISSUE THREAD

**Issue by NikNakk** [opensafely/immunosuppressant-meds-research#76]
@myatesrheum, I've got the STATA file working within the GitHub action. It's now failing because of the change in the high cost drug naming. I've updated the first bits (the redundant drops of columns we removed today and the recoding of missing), but there's still quite a bit to do further on. I don't have access to STATA other than by pushing to GitHub and watching the action, so would be grateful if you can pick this up now.

**Comment by myatesrheum** [comment]
Thanks @NikNakk, will do. Will wort drug name changes and output file paths, then I think it's there.

**Comment by NikNakk** [comment]
For now, I’ve put in a change directory (cd) command to the output folder because I didn’t want to have to manually change lots of output commands further down, but you may wish to do something else like putting the output directory into a variable and using it each time.

Best wishes,

Nick Kennedy
________________________________
