### ISSUE TITLE
*Medication codes* - Primary care Methotrexate oral

### ISSUE THREAD

**Issue by AnnaB45** [opensafely/immunosuppressant-meds-research#77]
Creating codelist for methotrexate prescribing in primary care.
Some previous discussion of this in [this issue](https://github.com/opensafely/codelist-development/issues/18).
Creating new issue to review primary care methotrexate prescribing only.
Key question from Brian MacKenna - Should we include all orals and injections prescribed in primary care in the same list?

**Comment by brianmackenna** [comment]
Oral methotrexate for checking @richiecroker  / @AnnaB45  I have included all liquids for completeness although our work on methotrexate tells us that prescribing of liquid will be minimal.

https://codelists.opensafely.org/builder/3eb9b7b2/

**Comment by richiecroker** [comment]
Checked - all seems fine to me.

**Comment by brianmackenna** [comment]
This is done -  @inglesp is just bug fixing this as I broke upload with duplicate codelist names.

**Comment by brianmackenna** [comment]
thanks Peter!

https://codelists.opensafely.org/codelist/opensafely/methotrexate-oral/738b5e12/
