### ISSUE TITLE
*medication* primary care injectable methotrexate

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#78]
see #77 for intial discussion. this is new issue for discussion of any topics arising with injecatble methotrexate

**Comment by brianmackenna** [comment]
@richiecroker @AnnaB45 for checking

https://codelists.opensafely.org/codelist/opensafely/merhotrexate-injectable/5a7beadd/

**Comment by brianmackenna** [comment]
@richiecroker or @AnnaB45 could you give this a quick look for accuracy please before I close?
https://codelists.opensafely.org/codelist/opensafely/methotrexate-injectable/3328044b/

**Comment by richiecroker** [comment]
I am happy with this codelist.
