### ISSUE TITLE
ciclosporin

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#83]
#14

**Comment by brianmackenna** [comment]
List here for someone to check https://codelists.opensafely.org/codelist/opensafely/ciclosporin-oral/4eea3776/

Also to confirm tha appropriate to exclude eye preparations?

**Comment by sinlangan** [comment]
Confirmed; agree exclude eye preparations

**Comment by brianmackenna** [comment]
dm+d list is available at https://codelists.opensafely.org/codelist/opensafely/ciclosporin-oral-dmd/4c961cc9/
