### ISSUE TITLE
**medication**  mycophenolate mofetil

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/immunosuppressant-meds-research#86]

**Comment by brianmackenna** [comment]
draft at https://codelists.opensafely.org/builder/12005134/

I have only included MMF as this is what our original [DMARDs list](https://codelists.opensafely.org/codelist/opensafely/dmards/2020-06-23/) is based on. However there are [approximately 600-700 prescriptions for mycophenolic acid in primary care](https://openprescribing.net/chemical/0802010N0/) each month......

questions: 

1. should we include mycophenolic acid in this list or make a separate list?
2. Why do we not have a high cost drugs list for these? I'm not up to speed on todays arrangements but these were previously cost passed through to commissioners. Has this changed since proliferation of brands and been subsumed into tariffs for things like transplants?

**Comment by richiecroker** [comment]
The costs for mycophenolate (and mycophenolic acid) are (I think) responsibility of NHSEI for [*transplant only*](https://www.england.nhs.uk/wp-content/uploads/2019/04/nhs-england-drugs-list-v14.1.pdf).  I'm not sure we've ever satisfactorily resolved the reimbursement/repatriation issues with it.

**Comment by catherinehsmith** [comment]
I would say include mycophenolic acid in this list (with MMF) - we would report them together

**Comment by brianmackenna** [comment]
MMF is in tariff in SE London so we may not expect to see it in high cost drugs. There is likely to be variety of arrangements of supply. This has implications for not identifying some patients therapy. Discussed and likely to be small number and recognised limitation in discussion

**Comment by brianmackenna** [comment]
BNF codelist at https://codelists.opensafely.org/codelist/opensafely/mycophenolate-mofetil/4984b78a/ and dm+d version at https://codelists.opensafely.org/codelist/opensafely/mycophenolate/30754455/

Couple of tidying points
- @richiecroker can you confirm you are definitely happy with this final version of lists
- @inglesp could you please change the name of the BNF codelist to `mycophenolate` i.e. remove mofetil (or tell me how I can do it if this is now permitted)
- @catherinehsmith do you have account on https://codelists.opensafely.org/ if you send me username I can add you to author list for future management/citations.

**Comment by catherinehsmith** [comment]
Hi Brian
Cathskin is my username
C

On 6 Mar 2021, at 12:57, Brian <notifications@github.com> wrote:

﻿

BNF codelist at https://codelists.opensafely.org/codelist/opensafely/mycophenolate-mofetil/4984b78a/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodelists.opensafely.org%2Fcodelist%2Fopensafely%2Fmycophenolate-mofetil%2F4984b78a%2F&data=04%7C01%7Ccatherine.smith%40kcl.ac.uk%7C2b70dc9bfc834ca0452708d8e09f67ec%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637506322563726474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vHRo%2B%2BAkaWKhp111CLWC1ELaZDGN6o%2FSTznr6BgkwsU%3D&reserved=0>

Couple of tidying points

  *   @richiecroker<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frichiecroker&data=04%7C01%7Ccatherine.smith%40kcl.ac.uk%7C2b70dc9bfc834ca0452708d8e09f67ec%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637506322563736468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ENkDkVulU7tTeLIZxDgfUHTjC4OmEOpoXhNJ16gpEL8%3D&reserved=0> can you confirm you are definitely happy with this final version
  *   @inglesp<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Finglesp&data=04%7C01%7Ccatherine.smith%40kcl.ac.uk%7C2b70dc9bfc834ca0452708d8e09f67ec%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637506322563746462%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9TIfi8nGM6NBn1ap5WOks6QI9s%2FT11GEHrF51VpCVg8%3D&reserved=0> could you please change the name of the codelist to mycophenolate i.e. remove mofetil (or tell me how I can do it if this is now permitted)
  *   @catherinehsmith<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcatherinehsmith&data=04%7C01%7Ccatherine.smith%40kcl.ac.uk%7C2b70dc9bfc834ca0452708d8e09f67ec%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637506322563746462%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C5TLPSHWxXF4wIbcVW18UFNmaePuiVYUUxAuSuLWKTE%3D&reserved=0> do you have account on https://codelists.opensafely.org/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodelists.opensafely.org%2F&data=04%7C01%7Ccatherine.smith%40kcl.ac.uk%7C2b70dc9bfc834ca0452708d8e09f67ec%7C8370cf1416f34c16b83c724071654356%7C0%7C0%7C637506322563756468%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WG4%2F%2Fsz0exhfhebC0ytsxrP9se%2F8mBy0gdCHAWywfJg%3D&reserved=0> if you send me username I can add you to author list for future management/citations.

**Comment by richiecroker** [comment]
@brianmackenna taken a look at the codelist - seems ok, but is it usual for the AMP code names not to have the full names - they all appear to have just "Mycophenolate mofetil 250mg capsules"  which is `name` rather than e.g. "Mycophenolate mofetil 250mg capsules (A A H Pharmaceuticals Ltd)" which is `description`?

**Comment by brianmackenna** [comment]
I think on OpenPrescribing we default to display the `description` in search results but on OpenCodelists we are using `name` - @inglesp is this right?

**Comment by inglesp** [comment]
Have renamed to [Mycophenolate (BNF)](https://codelists.opensafely.org/codelist/opensafely/mycophenolate-bnf/).

**Comment by inglesp** [comment]
> I think on OpenPrescribing we default to display the description in search results but on OpenCodelists we are using name - @inglesp is this right?

Yes, looks like it.

**Comment by brianmackenna** [comment]
Thanks everyone - great work 

https://codelists.opensafely.org/codelist/opensafely/mycophenolate/30754455/
